rango/urls.py
from django.conf.urls import include, url
from rango import views
#urlpatterns = patterns('',url(r'^$', views.index, name='index'))
app_name = 'rango'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^about/$',views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name = 'add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$',views.search, name='search'),
    url(r'^add_profile/$',views.register_profile,name='UserProfileForm'),
    url(r'^rango/profile/$',views.profile,name='profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^suggest_category/', views.suggest_category, name='suggest_category'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.conf import settings
#from registration.backends.simple.views import RegistrationView
# class MyRegistrationView(RegistrationView):
#     def get_success_url(self,request, user):
#         return '/rango/'

urlpatterns = [
    url('admin/', admin.site.urls),
    # url(r'^rango/', include('rango.urls')),
    url('rango/', include('rango.urls')),
    #url(r'^accounts/register/$',MyRegistrationView.as_view(),name='registration_register'),
    #url(r'^accounts/', include('registration.backends.simple.urls')),

]
# if settings.DEBUG:
#     urlpatterns + [url(
#         'django.views.static',
#         (r'media/(?P<path>.*)',
#         'serve',
#         {'document_root': settings.MEDIA_ROOT}), )]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings. )   
if settings.DEBUG:
    urlpatterns + [
        url('django.views.static', (r'media/(?P<path>.*)',
                                    'serve', {'document_root': settings.MEDIA_ROOT}),),
        url('django.views.static', (r'static/(?P<path>.*)',
                                    'static', {'document_root': settings.STATIC_ROOT}),)
    ]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True,blank=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    class Meta:
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    def __str__(self):
        return self.title
        
    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category,UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
    help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Category
        fields = ('name',)
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
    help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
    help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = Page
        exclude = ('category',)
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm
from rango.forms import UserForm, UserProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import datetime

from rango.bing_search import run_query


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

        if max_results > 0:
            if len(cat_list) > max_results:
                cat_list = cat_list[:max_results]
    return cat_list


def index(request):
    # context = RequestContext(request)
    # context_dict = {'boldmessage': "I am bold font from the context"}
    # return HttpResponse("<a href='/rango/about/'>About</a>")
    request.session.set_test_cookie()
    # -likes for descending likes for ascending
    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': pages_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    context_dict['cat_list']= Category.objects.order_by('-views')
    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    context = RequestContext(request)
    visit = int(request.COOKIES.get('visits', '1'))
    context_dict={'count':visit}
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/about.html', context_dict, context)

    # return HttpResponse('Rango Says:Here is the about page. <a href="/rango">Home</a>')


def show_category(request, category_name_slug):
    context_dict = {}
    # context_dict['result_list'] = None
    # context_dict['query'] = None
    # if request.method == 'POST':
    #     query = request.POST['query'].strip()
    #     if query:
    #         result_list = run_query(query)
    #         context_dict['result_list'] = result_list
    #         context_dict['query'] = query
    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['cat_list']= Category.objects.order_by('-views')
    except Category.DoesNotExist:
        pass
    # if not context_dict['query']:
    #     context_dict['query'] = category.name
    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    context_dict={'form':form}
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/add_category.html', context_dict)


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    form = PageForm()

    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)
    context_dict = {
        'form': form,
        'category': category
    }
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    context_dict={'user_form': user_form, 'profile_form': profile_form, 'registered': registered}
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/register.html',context_dict)


def user_login(request):
    context = RequestContext(request)
    context_dict=dict()
    context_dict['cat_list']= Category.objects.order_by('-views')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse('Your Rango account is disabled.')
        else:
            print("Invalid login details were provided. So we can't log the user in")
            return HttpResponse('Invalid login details supplied.')

    else:
        return render(request, 'rango/login.html', context_dict, context)


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(
        request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(
        last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


def search(request):
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list})


def register_profile(request):
    print("resister profile")


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture})

    if request.method == 'POST':
        form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
    context_dict={'userprofile': userprofile, 'selecteduser': user, 'form': form}
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/profile.html', context_dict)


def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views = page.views + 1
                page.save()
                url = page.url
            except:
                pass
    return redirect(url)


@login_required
def list_profiles(request):
    #    user_list = User.objects.all()
    userprofile_list = UserProfile.objects.all()
    context_dict={'userprofile_list': userprofile_list}
    context_dict['cat_list']= Category.objects.order_by('-views')
    return render(request, 'rango/list_profiles.html',context_dict)


def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
        cat_list = get_category_list(8, starts_with)

    return render(request, 'rango/cats.html', {'cats': cat_list})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
About
{% endblock %}
{% block body_block %}
<link rel="stylesheet" href="{% static "css/base.css" %}" /> 
<body>
    <h1>This is About page</h1>
    Visits: {{ count }} <button onClick="alert('You clicked the button using Javascript.');">
        Click Me - I run Javascript
    </button>  <button id="about-btn" class="ouch"> Click Me - I'm Javascript on Speed</button><br/>
    <p>YO BRO!</p><br/>
    <img src="{% static "wallmax.jpg" %}" alt="Picture in About" width="900"/> 
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <h1>Add a Category</h1>
        <div>
        <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
        </form>
        </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <div class="hero-unit">
        <h1>Add a page to the {{ category_name }} Category</h1>
        <br />
        <div class="container">
            <form class="span6" id="page_form" method="POST" action="/rango/category/{{ category.slug }}/add_page/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}<br/>
                {% endfor %}

                <br />
                <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load rango_template_tags %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

      <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
    <!-- <link href="../../static/bootstrap.css" rel="stylesheet">
    <link href="../../static/dashboard.css" rel="stylesheet">  -->

    <link href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">Your Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:list_profiles' %}">All Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/rango/logout/">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/rango/register/">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/rango/login/">Login</a>
            </li>
        {% endif %}
            <li class="pull navbar-toggler-right">
              <form action="/rango/search/" method="POST">
              {% csrf_token %}
                <input type="text" placeholder="Search" name="query" style="height: 35px;"/>
                <button type="submit" class="btn btn-success" style="height: 35px;">Go!</button>
              </form>
            </li>
        </ul>
      </div>
    </nav>

          <div class="container-fluid">
            <div class="row" style="padding: 15px;">
              <div class="col-sm-3 col-md-2 sidebar" style="background-color:  #aeb6bf ;">
      
                  <!-- <ul class="nav nav-pills flex-column">
                  <li class="nav-item">Type to find a category</li>
                    <form>
                    <li class="nav-item"><input class="search-query form-control" type="text"
                      name="suggestion" value="" id="suggestion" autocomplete="off" />
                    </li>
                  </form>
                </ul>
                  <hr /> -->
                  <div class="well sidebar-nav" style="padding: 10px;">
                    <strong>Category List</strong>
                      <ul class="nav nav-list">
                          {% if cat_list %}
                          <ul>
                              {% for category in cat_list %}
                              <li><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a> ({{category.likes}} likes)</li>
                              {% endfor %}
                          </ul>
                              {% else %}
                          <strong>There are no categories present.</strong>
                          {% endif %}
                      </ul>
                  </div>
            <div id="cats">
      </div>
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main" style="padding: 8px;">
         {% block body_block %}
         
         {% endblock %}
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>

   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <script src="https://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
<script src="{% static "rango-jquery.js" %}"></script> 
<script src="{% static "rango-ajax.js" %}"></script>

templates/rango/base_copy.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap-fluid-adj.css'%} " rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css'%} " rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/twd.ico'%}" />

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>


  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44397330-1', 'tangowithdjango.com');
  ga('send', 'pageview');

</script>

</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/rango/">Rango</a>

            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    {% if user.is_authenticated %}
                    <li class="navbar-text">Welcome, {{ user.username }}!</li>
                    <li><a href="/rango/profile/">Profile</a></li>
                    <li><a href="/rango/logout/">Logout</a></li>
                        {% else %}

                    <li><a href="/rango/register/">Register</a></li>
                    <li><a href="/rango/login/">Login</a></li>

                    {% endif %}
                </ul>

                <ul class="nav">
                    {% if user.is_authenticated %}
                    <!-- <li><a href="/rango/restricted/">Restricted</a></li> -->
                    <li><a href="/rango/add_category/">Add Category</a></li>
                    {% endif %}

                    <!--- <li><a href="/rango/search">Search</a></li> -->
                    <li><a href="http://www.tangowithdjango.com/">TWD</a></li>
                    <li><a href="http://www.tangowithdjango.com/book/">Book</a></li>
                    <li><a href="/rango/about/">About</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li></li>
                    <li></li>
                    {% block navbar %}
                    {% endblock %}
                </ul>

		<ul class="nav nav-list">
			<li class="nav-header">Find a Category</li>
			<form>
			<label></label>
			<li><input  class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
			</form>
		</ul>

        {% if cat_list %}
		    <div id="cats">
			    {% include 'rango/category_list.html' with cat_list=cat_list %}
		    </div>
	    {% endif %}
<!---
    <div id="cats">
		   {% if cat_list %}
			<ul class="nav nav-list"><li>Category List</li></ul>
			   {% include 'rango/category_list.html' with cat_list=cat_list %}
		   {% endif %}
		</div>
--->


            </div>
            <!--/.well -->

        </div>
        <!--/span-->
        <div class="span9">

            {% block body_block %}
            {% endblock %}

        </div>
        <!--/span-->
    </div>
    <!--/row-->

</div>
<!--/.fluid-container-->

<hr>

<footer>
    <div class="container">
        <p>&copy; Rango: How to Tango with Django 2013</p>
    </div>
</footer>


<hr/>


<script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/rango-ajax.js' %}"></script>

</body>
</html>

templates/rango/base_sample.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
{% load rango_template_tags %}
<html>
<head lang="en">
    <meta charset="UTF-8" />
    <title>Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}</title>
</head>
    <body>
        <div>
        {% block body_block %}

        {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'rango:index' %}">Home</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'rango:index' %}">Home</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            {% endif %}
            </ul>
        </div>
        <hr/>
    </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}
{% load staticfiles %}
{% block title_block %}
    {{ category.name }}
{% endblock %}
{% block body_block %}
    
    <div>
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
        <ul>
                {% for page in pages %}
                <li>
                <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                {% if page.views > 1 %}
                ({{ page.views }} views)
                {% elif page.views == 1 %}
                ({{ page.views }} view)
                {% endif %}
                </li>
                {% endfor %}
        </ul>
    {% else %}
        <strong>No pages currently in category.</strong>
    {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
    {% else %}
        The specified category does not exist!
    {% endif %}
    </div>
{% endblock %}

templates/rango/category_list.html
<ul class="nav nav-list">
        {% if cat_list %}
        {% for cat in cat_list %}
        <li><a href="/rango/category/{{ cat.url }}">{{ cat.name }}</a></li>
        {% endfor %}
        {% else %}
        <li>No categories at present.</li>
        {% endif %}
        </ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Rango
{% endblock %}
{% block body_block %}
    <h1 class="display-3">Rango says...</h1>
    <div>
        {% if user.is_authenticated %}
            hey... {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
    </div>
    <strong>Most liked Categories:</strong>
    <div>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a> ({{category.likes}} likes)</li>
            {% endfor %}
        </ul>
            {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
    </div>
    <strong>Most viewed Pages:</strong>
    <div>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a> ({{page.views}} views)</li>
            {% endfor %}
        </ul>
            {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}
    </div>
{% endblock %}